### ISSUE TITLE
[Improvement] add client_max_body_size 0 to nginx

### ISSUE THREAD

**Issue by hbokh** [ContainerSolutions/docker-registry-proxy#1]
In order to prevent HTTP 413 errors (_Request Entity Too Long_) like this:

```
FATA[0005] Error pushing to registry: Server error: 413 trying to push foo/bar blob - sha256:985c - etc. etc.
```

add this line to default.conf:

`client_max_body_size 0; # disable any limits to avoid HTTP 413 for large image uploads`

**Comment by tnolet** [comment]
yes, this is needed. All but the most minor pushes will fail otherwise
